[workspace]
authors = ["Cameron Riddell <cameron@dutc.io>"]
channels = ["conda-forge"]
name = "2025-10-31_r-to-python-dataframes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
polars = ">=1.34.0,<2"
r-base = ">=4.5.1,<4.6"
r-dplyr = ">=1.1.4,<2"
pandas = ">=2.3.3,<3"
